version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd slideshows && yarn start"
    ports:
     - "3000:3000"
  db:
   image: mariadb:10.5
   volumes:
    - ./mariadb/db_data:/var/lib/mysql
   ports:
       - "13306:3306"
   restart: always
   environment:
           MYSQL_ROOT_PASSWORD: root_password
volumes:
    db_data:
